/*
model from : https://polyhaven.com/a/marble_bust_01
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 public/model/bust/marble_bust_01_1k.gltf -t -r public 
*/

// import React from "react";
import { Center, useGLTF } from "@react-three/drei";
import { Mesh, MeshStandardMaterial } from "three";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    marble_bust_01: Mesh;
  };
  materials: {
    marble_bust_01: MeshStandardMaterial;
  };
  // animations: GLTFAction[]
};
export function BustModel(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF(
    "/model/bust/marble_bust_01_1k.gltf"
  ) as GLTFResult;

  return (
    <group {...props} dispose={null}>
      <Center>
        <mesh
          scale={10}
          castShadow
          geometry={nodes.marble_bust_01.geometry}
          material={materials.marble_bust_01}
          position={[0, 0.2, 0.15]}
        >
          {/* <MeshTransmissionMaterial
          transmission={1}
          roughness={0.3}
          metalness={0.15}
          chromaticAberration={0.85}
          backside={true}
          backsideThickness={1}
          thickness={2}
          ior={1}
          anisotropy={0.1}
        /> */}
        </mesh>
      </Center>
    </group>
  );
}

useGLTF.preload("/model/bust/marble_bust_01_1k.gltf");
